name: Integracion Continua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Obtener codigo del repositorio
      uses: actions/checkout@v3

    - name: 2. Preparar entorno Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: 3. Instalar dependencias
      run: npm install

    - name: 4. Ejecutar pruebas unitarias
      run: npm test